# Site setings
name: 'Gruzewski.Dev'
description: 'Chciałbym aby ta strona była miejscem gdzie będę mógł się z Wami dzielić moją wiedzą oraz moimi doświadczeniami. Znajdziecie tutaj wpisy związane z JVM, architekturą, testami oraz z projektami, które obecnie prowadzę.'
meta_description: ''
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: "https://gruzewski.dev"
baseurl: 
production_url:
disqus: 'gruzewski-dev'
mailchimp_url: '//dev.us7.list-manage.com/subscribe/post?u=f7a122ac8ec7d8eef9610d15a&amp;id=3cb00cdd8a'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 'UA-131731100-2'


# Author
author:
  name: 'Mateusz Grużewski'
  image: 'authorimage.jpg'
  greetings: 'Cześć!'
  description: "Fajnie, że tu trafiłeś, nawet jeśli przez przypadek to zostań, rozgość się, jesteś mile widziany. Dalsza rodzina nazywa mnie informatykiem, bliska programistą, sam określam się zaszczytnym mianem Software Developera.
   Programowanie jest moim sposobem na życie i przetrwanie, ale też pasją, której z chęcią się poddaję i zatracam.
    W swojej pracy mocno zwracam uwagę na czystość i przejrzystość kodu.
    Najważniejszym jednak jest to, że lubię dzielić się swoją wiedzą i jednocześnie poszerzać własne horyzonty.
    Na blogu poruszane będą zagadnienia związane z JVM, architekturą czy wspomnianym już czystym kodem."
  bio: ''

# Contact form setings
email: mateusz@gruzewski.dev
contact_page_description: "."
thankyou_page_description: "Twoja wiadomość została wysłana."

# Social links
twitter: 'MatGruzewski'
github: 'lshadown'
instagram: 'gruzewski.dev'
linkedin: 'mateuszgruzewski'

# Navigation
navigation:
  - text: O mnie
    url: /about
  - text: Wystąpienia
      url: /talks
  - text: Kontakt
      url: /contact
# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
